server:
  port: 8081
  servlet-path: /Velocity
# 配置velocity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: abc123
    type: com.alibaba.druid.pool.DruidDataSource
  velocity :
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    enabled: true
    prefix: /templates/
    suffix: .vm

