server:
  port: 8081
  servlet:
    context-path: /Log
butterfly:
  name: 岳泽霖
  age: 26
  description:  一个孤独的小孩子
#配置日志
mylog:
 run-time: 1 #运行时间超过1
 result-length: 10  # 结果就返回10
 exc-full-show: false   # 不展示全异常
