server:
  port: 8081
  servlet:
    context-path: /Stock
#配置 swagger
swagger:
  show: true
  production: false
  basic:
    # 开启验证
    enable: true
    # 账号和密码
    username: root
    password: abc123
